project:
  type: website
  output-dir: docs

website:
  title: "Operationalization of dynamic ocean management tools for US West Coast"
  search: true
  repo-url: https://github.com/joshcullen/CEG_operationalization
  repo-subdir: website
  repo-actions: [issue, source]
  bread-crumbs: false
  sidebar:
    style: docked
    contents:
      - text: Home
        href: index.qmd
      - text: Leatherback Sea Turtle
        href: leatherback.qmd
        contents:
          - lbst_cmems.qmd
  page-footer:
    left: |
      &copy; 2025 Josh Cullen
    right: |
      This page is built with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
  google-analytics: 
    tracking-id: "G-VJ65XWLC94"

toc: true
toc-depth: 5
  
  
format:
  html:
    theme: zephyr
    link-external-icon: true
    link-external-newwindow: true
    fig-align: center
    css: styles.css
    axe: true

execute: 
  warning: false
  message: false

editor: source

highlight-style: github
