
name: ROMS model workflow

on:
  # triggered on push to repo
  # push:
  #   branches: main
  # triggered by cron job
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.cronhub.io
    - cron:  '30 15 * * *'  #scheduled to run at 3:30 pm UTC every day
  # triggered by manual activation on GitHub repo website
  workflow_dispatch:

jobs:
  acquire_roms:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          metadata/
          data_acquisition/R/
          data_acquisition/netcdfs/roms_ncdfs/
        sparse-checkout-cone-mode: false # Set to false for more granular control

    - name: Check disk space
      run: wmic logicaldisk list brief

  #   - name: Install R
  #     uses: r-lib/actions/setup-r@v2
  #     with:
  #       r-version: '4.4.3'
  # 
  #   - name: Install R packages
  #     uses: r-lib/actions/setup-r-dependencies@v2
  #     with:
  #       cache-version: 4
  # 
  #   - name: Download ROMS data
  #     shell: Rscript {0}
  #     run: |
  #       source("data_acquisition/R/acquire_roms.R")
  #     working-directory: ${{ github.workspace }}
  # 
  #   - name: Commit and Push Changes
  #     run: |
  #       git config --global user.name "${{ github.actor }}"
  #       git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  # 
  #       git fetch origin gh-pages --depth=1
  #       git pull
  #       git add .
  #       git commit -m 'Added new ROMS files'
  #       git push
  # 
  # process_roms:
  #   runs-on: ubuntu-latest
  #   needs: acquire_roms
  #   env:
  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #   - name: Check out repository
  #     uses: actions/checkout@v4
  #     with:
  #       sparse-checkout: |
  #         metadata/
  #         data_processing/R/
  #         data_acquisition/netcdfs/roms_ncdfs/
  #         data_processing/ROMS/
  #       sparse-checkout-cone-mode: false # Set to false for more granular control
  #   
  #   - name: Pull in Latest Changes
  #     run: |
  #       git config --global user.name "${{ github.actor }}"
  #       git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  # 
  #       git pull
  # 
  #   - name: Install R
  #     uses: r-lib/actions/setup-r@v2
  #     with:
  #       r-version: '4.4.3'
  # 
  #   - name: Install R packages
  #     uses: r-lib/actions/setup-r-dependencies@v2
  #     with:
  #       cache-version: 4
  # 
  #   - name: Process ROMS netCDFs and created derived vars
  #     shell: Rscript {0}
  #     run: |
  #       source("data_processing/R/process_roms.R")
  #     working-directory: ${{ github.workspace }}
  # 
  #   - name: Commit and Push Changes
  #     run: |
  #       git config --global user.name "${{ github.actor }}"
  #       git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  # 
  #       git fetch origin gh-pages --depth=1
  #       git pull
  #       git add .
  #       git commit -m 'Processed ROMS files'
  #       git push
  #       
  # predict_ROMS:
  #   runs-on: ubuntu-latest
  #   needs: process_roms
  #   env:
  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #   - name: Check out repository
  #     uses: actions/checkout@v4
  #     with:
  #       sparse-checkout: |
  #         metadata/
  #         model_prediction/R/
  #         data_processing/ROMS/rasters/
  #         model_prediction/ROMS/
  #       sparse-checkout-cone-mode: true  # Set to false for more granular control
  # 
  #   - name: Pull in Latest Changes
  #     run: |
  #       git config --global user.name "${{ github.actor }}"
  #       git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  # 
  #       git pull
  #   
  #   - name: Install R
  #     uses: r-lib/actions/setup-r@v2
  #     with:
  #       r-version: '4.4.3'
  # 
  #   - name: Install R packages
  #     uses: r-lib/actions/setup-r-dependencies@v2
  #     with:
  #       cache-version: 4
  # 
  #   - name: Install rnaturalearthhires R package from GitHub
  #     shell: Rscript {0}
  #     run: |
  #       install.packages("remotes")
  #       remotes::install_github("ropensci/rnaturalearthhires")
  # 
  #   - name: Make predictions for ROMS tool
  #     shell: Rscript {0}
  #     run: |
  #       source("model_prediction/R/predict_ROMS.R")
  #     working-directory: ${{ github.workspace }}
  # 
  #   - name: Commit and Push Changes
  #     run: |
  #       git config --global user.name "${{ github.actor }}"
  #       git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  # 
  #       git fetch origin gh-pages --depth=1
  #       git pull
  #       git add .
  #       git commit -m 'Made predictions for ROMS tool'
  #       git push
  #       